#release configuration
#Sun Jul 05 10:54:29 JST 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.litt\:geff=1.1.1-SNAPSHOT
project.rel.org.litt\:geff=1.1.0
project.scm.org.litt\:geff.connection=scm\:git\:https\:github.com/live-image-tracking-tools/geff-java
project.scm.org.litt\:geff.developerConnection=scm\:git\:git@github.com\:live-image-tracking-tools/geff-java
project.scm.org.litt\:geff.tag=HEAD
project.scm.org.litt\:geff.url=https\://github.com/live-image-tracking-tools/geff-java
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=geff-1.1.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/live-image-tracking-tools/geff-java
